/**
 * Fallback word bank for offline/fast validation
 * Contains common 4+ letter English words
 * Used to reduce API calls to Datamuse
 */

/**
 * Common 4-letter words (high frequency)
 */
const FOUR_LETTER_WORDS = new Set([
  'ABLE', 'ACHE', 'ACRE', 'AGED', 'AIDE', 'AIMS', 'AIRS', 'AJAR', 'AKIN', 'ALES',
  'ALPS', 'ALTO', 'AMEN', 'AMID', 'AMPS', 'ANDY', 'ANEW', 'ANTI', 'ANTS', 'APES',
  'APEX', 'APPS', 'AQUA', 'ARCH', 'AREA', 'ARGS', 'ARIA', 'ARID', 'ARMS', 'ARMY',
  'ARTS', 'ASAP', 'ASIA', 'ASKS', 'ATOM', 'AUNT', 'AUTO', 'AVID', 'AWAY', 'AWED',
  'AXES', 'AXIS', 'BABY', 'BACK', 'BAGS', 'BAIL', 'BAIT', 'BAKE', 'BALD', 'BALL',
  'BAND', 'BANG', 'BANK', 'BARE', 'BARK', 'BARN', 'BARS', 'BASE', 'BASH', 'BASK',
  'BASS', 'BATH', 'BATS', 'BEAD', 'BEAK', 'BEAM', 'BEAN', 'BEAR', 'BEAT', 'BEDS',
  'BEEF', 'BEEN', 'BEER', 'BEES', 'BELL', 'BELT', 'BEND', 'BENT', 'BEST', 'BETA',
  'BIAS', 'BIKE', 'BILE', 'BILL', 'BIND', 'BINS', 'BIRD', 'BITE', 'BITS', 'BLAH',
  'BLED', 'BLEW', 'BLOB', 'BLOG', 'BLOW', 'BLUE', 'BLUR', 'BOAR', 'BOAT', 'BOBS',
  'BODY', 'BOIL', 'BOLD', 'BOLT', 'BOMB', 'BOND', 'BONE', 'BOOK', 'BOOM', 'BOOT',
  'BORE', 'BORN', 'BOSS', 'BOTH', 'BOUT', 'BOWL', 'BOYS', 'BRAD', 'BRAG', 'BRAN',
  'BRAT', 'BREW', 'BRIM', 'BROW', 'BUCK', 'BUDS', 'BUGS', 'BULB', 'BULK', 'BULL',
  'BUMP', 'BUNK', 'BUOY', 'BURN', 'BURP', 'BURY', 'BUSH', 'BUSY', 'BUYS', 'BUZZ',
  'BYTE', 'CAFE', 'CAGE', 'CAKE', 'CALF', 'CALL', 'CALM', 'CAME', 'CAMP', 'CANE',
  'CANS', 'CAPE', 'CAPS', 'CARD', 'CARE', 'CARP', 'CARS', 'CART', 'CASE', 'CASH',
  'CASK', 'CAST', 'CATS', 'CAVE', 'CELL', 'CHAT', 'CHEF', 'CHEW', 'CHIN', 'CHIP',
  'CHOP', 'CHUG', 'CITE', 'CITY', 'CLAD', 'CLAM', 'CLAN', 'CLAP', 'CLAW', 'CLAY',
  'CLIP', 'CLOD', 'CLOG', 'CLUB', 'CLUE', 'COAL', 'COAT', 'COAX', 'COCK', 'CODE',
  'COIL', 'COIN', 'COLD', 'COLE', 'COLT', 'COMA', 'COMB', 'COME', 'CONE', 'COOK',
  'COOL', 'COPE', 'COPY', 'CORD', 'CORE', 'CORK', 'CORN', 'COST', 'COSY', 'COUP',
  'COVE', 'COWS', 'COZY', 'CRAB', 'CRAM', 'CREW', 'CRIB', 'CROP', 'CROW', 'CRUX',
  'CUBE', 'CUBS', 'CUFF', 'CULT', 'CUPS', 'CURB', 'CURE', 'CURL', 'CURT', 'CUTE',
  'CUTS', 'DALE', 'DAME', 'DAMP', 'DARE', 'DARK', 'DARN', 'DART', 'DASH', 'DATA',
  'DATE', 'DAWN', 'DAYS', 'DAZE', 'DEAD', 'DEAF', 'DEAL', 'DEAN', 'DEAR', 'DEBT',
  'DECK', 'DEED', 'DEEM', 'DEEP', 'DEER', 'DEMO', 'DENY', 'DESK', 'DIAL', 'DICE',
  'DIED', 'DIET', 'DIME', 'DINE', 'DING', 'DINT', 'DIRE', 'DIRT', 'DISC', 'DISH',
  'DISK', 'DIVE', 'DOCK', 'DOCS', 'DODO', 'DOES', 'DOGS', 'DOLL', 'DOME', 'DONE',
  'DOOM', 'DOOR', 'DOPE', 'DOSE', 'DOTE', 'DOTS', 'DOVE', 'DOWN', 'DOZE', 'DRAB',
  'DRAG', 'DRAM', 'DRAW', 'DREW', 'DRIP', 'DROP', 'DRUG', 'DRUM', 'DUAL', 'DUCK',
  'DUDE', 'DUDS', 'DUEL', 'DUES', 'DUET', 'DULL', 'DULY', 'DUMB', 'DUMP', 'DUNE',
  'DUNG', 'DUNK', 'DUPE', 'DUSK', 'DUST', 'DUTY', 'DYED', 'EACH', 'EARL', 'EARN',
  'EARS', 'EASE', 'EAST', 'EASY', 'EATS', 'ECHO', 'EDGE', 'EDIT', 'EELS', 'EGGS',
  'EGOS', 'EMIT', 'EPIC', 'EVEN', 'EVER', 'EVIL', 'EXAM', 'EXEC', 'EXIT', 'EYED',
  'EYES', 'FACE', 'FACT', 'FADE', 'FAIL', 'FAIR', 'FAKE', 'FALL', 'FAME', 'FANG',
  'FANS', 'FARE', 'FARM', 'FAST', 'FATE', 'FATS', 'FAWN', 'FEAR', 'FEAT', 'FEED',
  'FEEL', 'FEES', 'FEET', 'FELL', 'FELT', 'FERN', 'FEST', 'FEUD', 'FIAT', 'FIGS',
  'FILE', 'FILL', 'FILM', 'FIND', 'FINE', 'FIRE', 'FIRM', 'FISH', 'FIST', 'FITS',
  'FIVE', 'FLAG', 'FLAK', 'FLAP', 'FLAT', 'FLAW', 'FLEA', 'FLED', 'FLEE', 'FLEW',
  'FLEX', 'FLIP', 'FLIT', 'FLOG', 'FLOW', 'FLUE', 'FLUX', 'FOAL', 'FOAM', 'FOES',
  'FOGS', 'FOIL', 'FOLD', 'FOLK', 'FOND', 'FONT', 'FOOD', 'FOOL', 'FOOT', 'FORD',
  'FORE', 'FORK', 'FORM', 'FORT', 'FOUL', 'FOUR', 'FOWL', 'FOXY', 'FRAY', 'FREE',
  'FRET', 'FROM', 'FROG', 'FUEL', 'FULL', 'FUME', 'FUND', 'FUNK', 'FURY', 'FUSE',
  'FUSS', 'FUZZ', 'GAIN', 'GAIT', 'GALA', 'GALE', 'GALL', 'GAME', 'GANG', 'GAPS',
  'GARB', 'GASH', 'GASP', 'GATE', 'GAVE', 'GAZE', 'GEAR', 'GEEK', 'GEMS', 'GENE',
  'GERM', 'GETS', 'GIFT', 'GILD', 'GILL', 'GILT', 'GIRL', 'GIST', 'GIVE', 'GLAD',
  'GLEE', 'GLEN', 'GLOW', 'GLUE', 'GLUT', 'GNAT', 'GNAW', 'GOAL', 'GOAT', 'GODS',
  'GOES', 'GOLD', 'GOLF', 'GONE', 'GONG', 'GOOD', 'GOOF', 'GORE', 'GOWN', 'GRAB',
  'GRAM', 'GRAY', 'GREW', 'GREY', 'GRID', 'GRIM', 'GRIN', 'GRIP', 'GRIT', 'GROW',
  'GRUB', 'GULF', 'GULL', 'GULP', 'GUMS', 'GUNS', 'GURU', 'GUSH', 'GUST', 'GUTS',
  'GUYS', 'GYMS', 'HACK', 'HAIL', 'HAIR', 'HALF', 'HALL', 'HALT', 'HAND', 'HANG',
  'HARD', 'HARE', 'HARM', 'HARP', 'HASH', 'HATE', 'HATS', 'HAUL', 'HAVE', 'HAWK',
  'HAZE', 'HAZY', 'HEAD', 'HEAL', 'HEAP', 'HEAR', 'HEAT', 'HECK', 'HEED', 'HEEL',
  'HEIR', 'HELD', 'HELL', 'HELM', 'HELP', 'HEMP', 'HENS', 'HERB', 'HERD', 'HERE',
  'HERO', 'HERS', 'HICK', 'HIDE', 'HIGH', 'HIKE', 'HILL', 'HILT', 'HIND', 'HINT',
  'HIRE', 'HISS', 'HITS', 'HIVE', 'HOAX', 'HOLD', 'HOLE', 'HOLY', 'HOME', 'HONE',
  'HOOD', 'HOOF', 'HOOK', 'HOOP', 'HOOT', 'HOPE', 'HOPS', 'HORN', 'HOSE', 'HOST',
  'HOUR', 'HUGE', 'HUGS', 'HULK', 'HULL', 'HUMS', 'HUNG', 'HUNK', 'HUNT', 'HURL',
  'HURT', 'HUSH', 'HUSK', 'HUTS', 'HYMN', 'HYPE', 'ICON', 'IDEA', 'IDLE', 'IDOL',
  'IFFY', 'INCH', 'INFO', 'INKS', 'INNS', 'INTO', 'IOTA', 'IRIS', 'IRON', 'ISLE',
  'ITCH', 'ITEM', 'JABS', 'JACK', 'JADE', 'JAIL', 'JAMS', 'JARS', 'JAWS', 'JAZZ',
  'JEER', 'JERK', 'JEST', 'JETS', 'JIGS', 'JIVE', 'JOBS', 'JOCK', 'JOGS', 'JOIN',
  'JOKE', 'JOLT', 'JOTS', 'JOWL', 'JOYS', 'JUDO', 'JUGS', 'JUMP', 'JUNE', 'JUNK',
  'JURY', 'JUST', 'JUTE', 'KALE', 'KEEN', 'KEEP', 'KEGS', 'KEPT', 'KEYS', 'KHAN',
  'KICK', 'KIDS', 'KILL', 'KILN', 'KILT', 'KIND', 'KING', 'KINK', 'KISS', 'KITE',
  'KITS', 'KNEE', 'KNEW', 'KNIT', 'KNOB', 'KNOT', 'KNOW', 'LABS', 'LACE', 'LACK',
  'LACY', 'LADS', 'LADY', 'LAID', 'LAIR', 'LAKE', 'LAMB', 'LAME', 'LAMP', 'LAND',
  'LANE', 'LAPS', 'LARD', 'LARK', 'LASH', 'LASS', 'LAST', 'LATE', 'LAUD', 'LAVA',
  'LAWN', 'LAWS', 'LAYS', 'LAZY', 'LEAD', 'LEAF', 'LEAK', 'LEAN', 'LEAP', 'LEAS',
  'LEER', 'LEFT', 'LEGS', 'LEND', 'LENS', 'LENT', 'LESS', 'LEST', 'LETS', 'LEVY',
  'LIAR', 'LICE', 'LICK', 'LIDS', 'LIED', 'LIEN', 'LIES', 'LIEU', 'LIFE', 'LIFT',
  'LIKE', 'LILT', 'LILY', 'LIMB', 'LIME', 'LIMP', 'LINE', 'LINK', 'LINT', 'LION',
  'LIPS', 'LISP', 'LIST', 'LITE', 'LIVE', 'LOAD', 'LOAF', 'LOAM', 'LOAN', 'LOBE',
  'LOBS', 'LOCK', 'LOFT', 'LOGE', 'LOGO', 'LOGS', 'LOIN', 'LONE', 'LONG', 'LOOK',
  'LOOM', 'LOOP', 'LOOT', 'LORD', 'LORE', 'LOSE', 'LOSS', 'LOST', 'LOTS', 'LOUD',
  'LOVE', 'LOWS', 'LUCK', 'LUGE', 'LULL', 'LUMP', 'LUNG', 'LURE', 'LURK', 'LUSH',
  'LUST', 'LUTE', 'LYNX', 'LYRE', 'MACE', 'MACH', 'MADE', 'MAGE', 'MAID', 'MAIL',
  'MAIM', 'MAIN', 'MAKE', 'MALE', 'MALL', 'MALT', 'MAMA', 'MANE', 'MANS', 'MANY',
  'MAPS', 'MARE', 'MARK', 'MARS', 'MART', 'MASH', 'MASK', 'MASS', 'MAST', 'MATE',
  'MATH', 'MATS', 'MAUL', 'MAZE', 'MEAD', 'MEAL', 'MEAN', 'MEAT', 'MEEK', 'MEET',
  'MELD', 'MELT', 'MEMO', 'MEND', 'MENU', 'MEOW', 'MERE', 'MESH', 'MESS', 'MICA',
  'MICE', 'MILD', 'MILE', 'MILK', 'MILL', 'MIME', 'MIND', 'MINE', 'MINK', 'MINT',
  'MIRE', 'MISS', 'MIST', 'MITE', 'MITT', 'MOAN', 'MOAT', 'MOCK', 'MODE', 'MOLD',
  'MOLE', 'MOLT', 'MONK', 'MOOD', 'MOON', 'MOOR', 'MOOT', 'MOPE', 'MOPS', 'MORE',
  'MORN', 'MOSS', 'MOST', 'MOTH', 'MOVE', 'MUCH', 'MUCK', 'MUDS', 'MUFF', 'MUGS',
  'MULE', 'MULL', 'MUMM', 'MUMS', 'MUNG', 'MURK', 'MUSE', 'MUSH', 'MUSK', 'MUST',
  'MUTE', 'MUTT', 'MYTH', 'NABS', 'NAGS', 'NAIL', 'NAME', 'NAPE', 'NAPS', 'NAVY',
  'NEAR', 'NEAT', 'NECK', 'NEED', 'NEON', 'NEST', 'NETS', 'NEWS', 'NEWT', 'NEXT',
  'NICE', 'NICK', 'NIGH', 'NINE', 'NIPS', 'NODE', 'NODS', 'NOEL', 'NONE', 'NOOK',
  'NOON', 'NOPE', 'NORM', 'NOSE', 'NOTE', 'NOUN', 'NOVA', 'NUBS', 'NUDE', 'NULL',
  'NUMB', 'NUNS', 'NUTS', 'OAFS', 'OAKS', 'OARS', 'OATH', 'OATS', 'OBEY', 'ODDS',
  'ODES', 'ODOR', 'OFFS', 'OGLE', 'OGRE', 'OILS', 'OILY', 'OKAY', 'OLDS', 'OMEN',
  'OMIT', 'ONCE', 'ONES', 'ONLY', 'ONTO', 'ONUS', 'OOZE', 'OPAL', 'OPEN', 'OPTS',
  'OPUS', 'ORAL', 'ORBS', 'ORCA', 'ORES', 'OURS', 'OUST', 'OUTS', 'OVAL', 'OVEN',
  'OVER', 'OWED', 'OWES', 'OWLS', 'OWNS', 'OXEN', 'PACE', 'PACK', 'PACT', 'PADS',
  'PAGE', 'PAID', 'PAIL', 'PAIN', 'PAIR', 'PALE', 'PALM', 'PALS', 'PANE', 'PANG',
  'PANS', 'PANT', 'PAPA', 'PARE', 'PARK', 'PART', 'PASS', 'PAST', 'PATE', 'PATH',
  'PATS', 'PAVE', 'PAWN', 'PAYS', 'PEAK', 'PEAL', 'PEAR', 'PEAS', 'PEAT', 'PECK',
  'PEEL', 'PEER', 'PEGS', 'PELT', 'PENS', 'PENT', 'PEON', 'PERK', 'PERM', 'PERT',
  'PEST', 'PETS', 'PEWS', 'PICK', 'PIED', 'PIER', 'PIES', 'PIGS', 'PIKE', 'PILE',
  'PILL', 'PINE', 'PING', 'PINK', 'PINT', 'PION', 'PIPE', 'PISS', 'PITA', 'PITH',
  'PITS', 'PITY', 'PLAN', 'PLAY', 'PLEA', 'PLED', 'PLOD', 'PLOT', 'PLOW', 'PLOY',
  'PLUG', 'PLUM', 'PLUS', 'POCK', 'PODS', 'POEM', 'POET', 'POKE', 'POLE', 'POLL',
  'POLO', 'POMP', 'POND', 'PONY', 'POOH', 'POOL', 'POOR', 'POPE', 'POPS', 'PORE',
  'PORK', 'PORN', 'PORT', 'POSE', 'POSH', 'POST', 'POSY', 'POTS', 'POUR', 'POUT',
  'PRAY', 'PREP', 'PREY', 'PRIG', 'PRIM', 'PROD', 'PROF', 'PROM', 'PROP', 'PROW',
  'PRUNE', 'PUBS', 'PUCK', 'PUFF', 'PUGS', 'PUKE', 'PULL', 'PULP', 'PUMA', 'PUMP',
  'PUNK', 'PUNS', 'PUNY', 'PUPA', 'PUPS', 'PURE', 'PURR', 'PUSH', 'PUTS', 'PUTT',
  'QUAD', 'QUAY', 'QUIT', 'QUIZ', 'RACE', 'RACK', 'RAFT', 'RAGE', 'RAGS', 'RAID',
  'RAIL', 'RAIN', 'RAKE', 'RAMP', 'RAMS', 'RANG', 'RANK', 'RANT', 'RAPE', 'RARE',
  'RASH', 'RASP', 'RATE', 'RATS', 'RAVE', 'RAYS', 'RAZE', 'READ', 'REAL', 'REAM',
  'REAP', 'REAR', 'REDO', 'REDS', 'REED', 'REEF', 'REEK', 'REEL', 'REFS', 'REIN',
  'RELY', 'REND', 'RENT', 'REPS', 'REST', 'REVS', 'RIBS', 'RICE', 'RICH', 'RIDE',
  'RIDS', 'RIFE', 'RIFT', 'RIGS', 'RILE', 'RIMS', 'RIND', 'RING', 'RINK', 'RIOT',
  'RIPE', 'RISE', 'RISK', 'RITE', 'ROAD', 'ROAM', 'ROAR', 'ROBE', 'ROCK', 'RODE',
  'RODS', 'ROGUE', 'ROLE', 'ROLL', 'ROMP', 'ROOF', 'ROOK', 'ROOM', 'ROOT', 'ROPE',
  'ROSE', 'ROSY', 'ROTS', 'ROUE', 'ROUT', 'ROVE', 'ROWS', 'RUBS', 'RUBY', 'RUDE',
  'RUIN', 'RULE', 'RUMP', 'RUMS', 'RUNG', 'RUNS', 'RUNT', 'RUSE', 'RUSH', 'RUST',
  'RUTS', 'SACK', 'SAFE', 'SAGA', 'SAGE', 'SAGS', 'SAID', 'SAIL', 'SAKE', 'SALE',
  'SALT', 'SAME', 'SAND', 'SANE', 'SANG', 'SANK', 'SAPS', 'SASH', 'SASS', 'SATE',
  'SAVE', 'SAWS', 'SAYS', 'SCAB', 'SCAM', 'SCAN', 'SCAR', 'SCAT', 'SEAL', 'SEAM',
  'SEAR', 'SEAS', 'SEAT', 'SECT', 'SEED', 'SEEK', 'SEEM', 'SEEN', 'SEEP', 'SEER',
  'SEES', 'SELF', 'SELL', 'SEMI', 'SEND', 'SENT', 'SEPT', 'SERA', 'SERF', 'SETS',
  'SEWN', 'SEWS', 'SHAD', 'SHAG', 'SHAM', 'SHAW', 'SHED', 'SHIN', 'SHIP', 'SHOD',
  'SHOE', 'SHOP', 'SHOT', 'SHOW', 'SHUN', 'SHUT', 'SICK', 'SIDE', 'SIFT', 'SIGH',
  'SIGN', 'SILK', 'SILL', 'SILO', 'SILT', 'SING', 'SINK', 'SIPS', 'SIRE', 'SITE',
  'SITS', 'SIZE', 'SKEW', 'SKID', 'SKIM', 'SKIN', 'SKIP', 'SKIT', 'SLAB', 'SLAM',
  'SLAP', 'SLAT', 'SLAW', 'SLAY', 'SLED', 'SLEW', 'SLID', 'SLIM', 'SLIP', 'SLIT',
  'SLOB', 'SLOE', 'SLOG', 'SLOP', 'SLOT', 'SLOW', 'SLUE', 'SLUG', 'SLUM', 'SLUR',
  'SMOG', 'SMUG', 'SNAG', 'SNAP', 'SNIP', 'SNOB', 'SNOT', 'SNOW', 'SNUB', 'SNUG',
  'SOAK', 'SOAP', 'SOAR', 'SOBS', 'SODA', 'SODS', 'SOFA', 'SOFT', 'SOIL', 'SOLD',
  'SOLE', 'SOLO', 'SOME', 'SONG', 'SONS', 'SOON', 'SOOT', 'SORE', 'SORT', 'SOUL',
  'SOUP', 'SOUR', 'SOWN', 'SOWS', 'SOYA', 'SPAM', 'SPAN', 'SPAR', 'SPAT', 'SPEC',
  'SPED', 'SPIN', 'SPIT', 'SPOT', 'SPRY', 'SPUD', 'SPUN', 'SPUR', 'STAB', 'STAG',
  'STAR', 'STAT', 'STAY', 'STEM', 'STEP', 'STEW', 'STIR', 'STOP', 'STOW', 'STUB',
  'STUD', 'STUN', 'SUBS', 'SUCH', 'SUDS', 'SUED', 'SUET', 'SUIT', 'SULK', 'SUMS',
  'SUNG', 'SUNK', 'SUNS', 'SURF', 'SWAB', 'SWAG', 'SWAM', 'SWAN', 'SWAP', 'SWAT',
  'SWAY', 'SWIM', 'SWOT', 'SWUM', 'SYNC', 'TABS', 'TACK', 'TACO', 'TACT', 'TAGS',
  'TAIL', 'TAKE', 'TALE', 'TALK', 'TALL', 'TAME', 'TAMP', 'TANG', 'TANK', 'TAPE',
  'TAPS', 'TARE', 'TARN', 'TARP', 'TART', 'TASK', 'TAUT', 'TAXI', 'TEAK', 'TEAL',
  'TEAM', 'TEAR', 'TEAS', 'TEAT', 'TECH', 'TEEM', 'TEEN', 'TEES', 'TELL', 'TEMP',
  'TEND', 'TENS', 'TENT', 'TERM', 'TERN', 'TEST', 'TEXT', 'THAN', 'THAT', 'THAW',
  'THEE', 'THEM', 'THEN', 'THEY', 'THIN', 'THIS', 'THOU', 'THUD', 'THUG', 'THUS',
  'TICK', 'TIDE', 'TIDY', 'TIED', 'TIER', 'TIES', 'TIFF', 'TILE', 'TILL', 'TILT',
  'TIME', 'TINE', 'TING', 'TINS', 'TINT', 'TINY', 'TIPS', 'TIRE', 'TOAD', 'TOCK',
  'TOES', 'TOFF', 'TOFU', 'TOGA', 'TOGS', 'TOIL', 'TOKE', 'TOLD', 'TOLL', 'TOMB',
  'TOME', 'TONE', 'TONG', 'TONS', 'TONY', 'TOOK', 'TOOL', 'TOOT', 'TOPS', 'TORE',
  'TORN', 'TORT', 'TOSS', 'TOTE', 'TOUR', 'TOUT', 'TOWN', 'TOYS', 'TRAM', 'TRAP',
  'TRAY', 'TREE', 'TREK', 'TRIM', 'TRIO', 'TRIP', 'TROD', 'TROT', 'TROY', 'TRUE',
  'TSAR', 'TUBA', 'TUBE', 'TUBS', 'TUCK', 'TUFT', 'TUGS', 'TUNA', 'TUNE', 'TUNG',
  'TUNS', 'TURF', 'TURN', 'TUSK', 'TUTU', 'TWIG', 'TWIN', 'TWIT', 'TYPE', 'TZAR',
  'UGLY', 'UNDO', 'UNIT', 'UNTO', 'UPON', 'UREA', 'URGE', 'URNS', 'USED', 'USER',
  'USES', 'VAIN', 'VALE', 'VANE', 'VANS', 'VARY', 'VASE', 'VAST', 'VATS', 'VEAL',
  'VEER', 'VEIL', 'VEIN', 'VEND', 'VENT', 'VERB', 'VERY', 'VEST', 'VETO', 'VETS',
  'VIAL', 'VICE', 'VIED', 'VIES', 'VIEW', 'VILE', 'VINE', 'VINO', 'VISE', 'VOID',
  'VOLT', 'VOTE', 'VOWS', 'WADE', 'WADS', 'WAFT', 'WAGE', 'WAGS', 'WAIL', 'WAIT',
  'WAKE', 'WALK', 'WALL', 'WAND', 'WANE', 'WANT', 'WARD', 'WARE', 'WARM', 'WARN',
  'WARP', 'WARS', 'WART', 'WARY', 'WASH', 'WASP', 'WAVE', 'WAVY', 'WAXY', 'WAYS',
  'WEAK', 'WEAN', 'WEAR', 'WEBS', 'WEDS', 'WEED', 'WEEK', 'WEEP', 'WEFT', 'WEIR',
  'WELL', 'WELT', 'WENT', 'WEPT', 'WERE', 'WEST', 'WETS', 'WHAM', 'WHAT', 'WHEN',
  'WHET', 'WHEY', 'WHIG', 'WHIM', 'WHIP', 'WHIR', 'WHIT', 'WHIZ', 'WHOM', 'WICK',
  'WIDE', 'WIFE', 'WIGS', 'WILD', 'WILE', 'WILL', 'WILT', 'WILY', 'WIND', 'WINE',
  'WING', 'WINK', 'WINS', 'WIPE', 'WIRE', 'WIRY', 'WISE', 'WISH', 'WISP', 'WITH',
  'WITS', 'WOES', 'WOKE', 'WOKS', 'WOLF', 'WOMB', 'WONT', 'WOOD', 'WOOF', 'WOOL',
  'WOOS', 'WORD', 'WORE', 'WORK', 'WORM', 'WORN', 'WORT', 'WOVE', 'WRAP', 'WREN',
  'WRIT', 'WUSS', 'YALE', 'YANK', 'YARD', 'YARN', 'YAWN', 'YEAR', 'YELL', 'YELP',
  'YEPS', 'YETI', 'YEWS', 'YOGA', 'YOGI', 'YOKE', 'YOLK', 'YOUR', 'YOWL', 'YOYO',
  'YUCK', 'YULE', 'YURT', 'ZANY', 'ZAPS', 'ZEAL', 'ZEBU', 'ZEDS', 'ZERO', 'ZEST',
  'ZETA', 'ZINC', 'ZING', 'ZION', 'ZIPS', 'ZITS', 'ZONE', 'ZONK', 'ZOOM', 'ZOOS',
]);

/**
 * Common 5+ letter words (selected high frequency)
 */
const LONGER_WORDS = new Set([
  'ABOUT', 'ABOVE', 'ABUSE', 'ACTOR', 'ACUTE', 'ADMIT', 'ADOPT', 'ADULT', 'AFTER',
  'AGAIN', 'AGENT', 'AGREE', 'AHEAD', 'ALARM', 'ALBUM', 'ALERT', 'ALIGN', 'ALIKE',
  'ALIVE', 'ALLOW', 'ALONE', 'ALONG', 'ALTER', 'AMBER', 'AMEND', 'AMONG', 'AMPLE',
  'ANGEL', 'ANGER', 'ANGLE', 'ANGRY', 'ANKLE', 'ANNOY', 'APART', 'APPLE', 'APPLY',
  'APRIL', 'ARENA', 'ARGUE', 'ARISE', 'ARMOR', 'AROMA', 'AROSE', 'ARRAY', 'ARROW',
  'ASIDE', 'ASSET', 'ATLAS', 'ATTIC', 'AUDIO', 'AVOID', 'AWAKE', 'AWARD', 'AWARE',
  'BADLY', 'BAKER', 'BANKS', 'BASIC', 'BASIN', 'BASIS', 'BATCH', 'BEACH', 'BEAST',
  'BEGAN', 'BEGIN', 'BEING', 'BELOW', 'BENCH', 'BILLY', 'BIRTH', 'BLACK', 'BLADE',
  'BLAME', 'BLANK', 'BLAST', 'BLEED', 'BLEND', 'BLESS', 'BLIND', 'BLINK', 'BLOCK',
  'BLOOD', 'BLOOM', 'BOARD', 'BOAST', 'BONUS', 'BOOST', 'BOOTH', 'BOUND', 'BRAIN',
  'BRAND', 'BRASS', 'BRAVE', 'BREAD', 'BREAK', 'BREED', 'BRICK', 'BRIDE', 'BRIEF',
  'BRING', 'BROAD', 'BROKE', 'BROWN', 'BRUSH', 'BUILD', 'BUILT', 'BUNCH', 'BURST',
  'BUYER', 'CABLE', 'CALIF', 'CANAL', 'CANDY', 'CARGO', 'CAROL', 'CARRY', 'CATCH',
  'CAUSE', 'CHAIN', 'CHAIR', 'CHAOS', 'CHARM', 'CHART', 'CHASE', 'CHEAP', 'CHECK',
  'CHEEK', 'CHEER', 'CHESS', 'CHEST', 'CHIEF', 'CHILD', 'CHINA', 'CHOSE', 'CIVIC',
  'CIVIL', 'CLAIM', 'CLASS', 'CLEAN', 'CLEAR', 'CLERK', 'CLICK', 'CLIFF', 'CLIMB',
  'CLOCK', 'CLOSE', 'CLOTH', 'CLOUD', 'COACH', 'COAST', 'COLON', 'COLOR', 'COUCH',
  'COULD', 'COUNT', 'COURT', 'COVER', 'CRACK', 'CRAFT', 'CRASH', 'CRAZY', 'CREAM',
  'CREEK', 'CRIME', 'CRISP', 'CROSS', 'CROWD', 'CROWN', 'CRUDE', 'CRUSH', 'CURVE',
  'CYCLE', 'DAILY', 'DAIRY', 'DANCE', 'DATED', 'DEALT', 'DEATH', 'DEBUT', 'DELAY',
  'DELTA', 'DENSE', 'DEPTH', 'DEVIL', 'DIARY', 'DIRTY', 'DOING', 'DOUBT', 'DOZEN',
  'DRAFT', 'DRAIN', 'DRAMA', 'DRANK', 'DRAWN', 'DREAM', 'DRESS', 'DRIED', 'DRILL',
  'DRINK', 'DRIVE', 'DROVE', 'DROWN', 'DRUNK', 'DUCTS', 'DUSTY', 'DYING', 'EAGER',
  'EAGLE', 'EARLY', 'EARTH', 'EIGHT', 'EJECT', 'ELDER', 'ELECT', 'EMPTY', 'ENEMY',
  'ENJOY', 'ENTER', 'ENTRY', 'EQUAL', 'EQUIP', 'ERROR', 'ESSAY', 'ETHIC', 'EVENT',
  'EVERY', 'EXACT', 'EXAMS', 'EXCEL', 'EXIST', 'EXTRA', 'FAITH', 'FALSE', 'FANCY',
  'FATAL', 'FAULT', 'FAVOR', 'FENCE', 'FERRY', 'FEVER', 'FEWER', 'FIBER', 'FIELD',
  'FIERY', 'FIFTH', 'FIFTY', 'FIGHT', 'FINAL', 'FIRST', 'FIXED', 'FLAME', 'FLASH',
  'FLEET', 'flesh', 'FLIGHT', 'FLOAT', 'FLOOD', 'FLOOR', 'FLORA', 'FLOUR', 'FLUID',
  'FLUSH', 'FOCAL', 'FOCUS', 'FOLKS', 'FORCE', 'FORGE', 'FORUM', 'FOUND', 'FRAME',
  'FRANK', 'FRAUD', 'FRESH', 'FRONT', 'FROST', 'FRUIT', 'FULLY', 'FUNNY', 'GIANT',
  'GIVEN', 'GLASS', 'GLOBE', 'GLOOM', 'GLORY', 'GLOVE', 'GOING', 'GRACE', 'GRADE',
  'GRAIN', 'GRAND', 'GRANT', 'GRAPH', 'GRASP', 'GRASS', 'GRAVE', 'GREAT', 'GREED',
  'GREEN', 'GREET', 'GRIEF', 'GRILL', 'GRIND', 'GROAN', 'GROSS', 'GROUP', 'GROVE',
  'GROWN', 'GUARD', 'GUESS', 'GUEST', 'GUIDE', 'GUILD', 'GUILT', 'HABIT', 'HANDY',
  'HAPPY', 'HARSH', 'HASTE', 'HASTY', 'HAUNT', 'HAVEN', 'HEART', 'HEAVY', 'HEDGE',
  'HELLO', 'HENCE', 'HENRY', 'HINGE', 'HOBBY', 'HONEY', 'HONOR', 'HORSE', 'HOTEL',
  'HOUSE', 'HUMAN', 'HUMOR', 'HURRY', 'IDEAL', 'IMAGE', 'IMPLY', 'INDEX', 'INNER',
  'INPUT', 'ISSUE', 'JIMMY', 'JOINT', 'JONES', 'JUDGE', 'JUICE', 'KNOWN', 'LABEL',
  'LABOR', 'LACKS', 'LARGE', 'LASER', 'LATER', 'LAUGH', 'LAYER', 'LEARN', 'LEASE',
  'LEAST', 'LEAVE', 'LEGAL', 'LEMON', 'LEVEL', 'LEWIS', 'LIGHT', 'LIMIT', 'LINED',
  'LINKS', 'LIVES', 'LOCAL', 'LOGIC', 'LOOSE', 'LOTUS', 'LOWER', 'LOYAL', 'LUCKY',
  'LUNAR', 'LUNCH', 'LYING', 'MAGIC', 'MAJOR', 'MAKER', 'MANOR', 'MARCH', 'MARRY',
  'MATCH', 'MAYBE', 'MAYOR', 'MEANS', 'MEANT', 'MEDAL', 'MEDIA', 'MELEE', 'MERCY',
  'MERGE', 'MERIT', 'MERRY', 'METAL', 'METER', 'METRO', 'MIGHT', 'MINOR', 'MINUS',
  'MIXED', 'MODEL', 'MONEY', 'MONTH', 'MORAL', 'MOTOR', 'MOUNT', 'MOUSE', 'MOUTH',
  'MOVED', 'MOVIE', 'MUSIC', 'NAKED', 'NAMED', 'NARROW', 'NASTY', 'NAVAL', 'NEEDS',
  'NERVE', 'NEVER', 'NEWLY', 'NIGHT', 'NINTH', 'NOBLE', 'NOISE', 'NORTH', 'NOTCH',
  'NOTED', 'NOVEL', 'NURSE', 'OCCUR', 'OCEAN', 'OFFER', 'OFTEN', 'ORDER', 'ORGAN',
  'OTHER', 'OUGHT', 'OUTER', 'OUTPUT', 'OWNER', 'OXIDE', 'OZONE', 'PACED', 'PANEL',
  'PANIC', 'PAPER', 'PARTY', 'PASTE', 'PATCH', 'PAUSE', 'PEACE', 'PENNY', 'PHASE',
  'PHONE', 'PHOTO', 'PIANO', 'PIECE', 'PILOT', 'PINCH', 'PITCH', 'PIXEL', 'PLACE',
  'PLAIN', 'PLANE', 'PLANT', 'PLATE', 'PLAZA', 'PLEAS', 'PLUCK', 'POINT', 'POLAR',
  'POKER', 'POLITE', 'POUND', 'POWER', 'PRESS', 'PRICE', 'PRIDE', 'PRIME', 'PRINT',
  'PRIOR', 'PRISM', 'PRIZE', 'PROBE', 'PRONE', 'PROOF', 'PROUD', 'PROVE', 'PROXY',
  'PULSE', 'PUNCH', 'PUPIL', 'PURSE', 'QUEEN', 'QUERY', 'QUEST', 'QUEUE', 'QUICK',
  'QUIET', 'QUILT', 'QUITE', 'QUOTA', 'QUOTE', 'RADIO', 'RAINY', 'RAISE', 'RALLY',
  'RANCH', 'RANGE', 'RAPID', 'RATIO', 'REACH', 'REACT', 'READY', 'REALM', 'REBEL',
  'REFER', 'REIGN', 'RELAX', 'RELAY', 'REPLY', 'RESET', 'RIDER', 'RIDGE', 'RIFLE',
  'RIGHT', 'RIGID', 'RISKY', 'RIVAL', 'RIVER', 'ROAST', 'ROBIN', 'ROBOT', 'ROCKY',
  'ROGER', 'ROMAN', 'ROUGH', 'ROUND', 'ROUTE', 'ROYAL', 'RUGBY', 'RULER', 'RURAL',
  'SAFER', 'SAINT', 'SALAD', 'SAUCE', 'SCALE', 'SCARE', 'SCARY', 'SCENE', 'SCENT',
  'SCOPE', 'SCORE', 'SCOUT', 'SCRAP', 'SCREW', 'SEIZE', 'SENSE', 'SERVE', 'SETUP',
  'SEVEN', 'SHADE', 'SHAFT', 'SHAKE', 'SHALL', 'SHAME', 'SHAPE', 'SHARE', 'SHARP',
  'SHEAR', 'SHEEP', 'SHEER', 'SHEET', 'SHELF', 'SHELL', 'SHIFT', 'SHINE', 'SHIRT',
  'SHOCK', 'SHOOT', 'SHORE', 'SHORT', 'SHOUT', 'SHOWN', 'SHRUG', 'SIDED', 'SIEGE',
  'SIGHT', 'SIGMA', 'SILLY', 'SINCE', 'SIXTH', 'SIZED', 'SKATE', 'SKILL', 'SKIRT',
  'SKULL', 'SLACK', 'SLASH', 'SLATE', 'SLAVE', 'SLEEK', 'SLEEP', 'SLEPT', 'SLICE',
  'SLIDE', 'SLOPE', 'SMALL', 'SMART', 'SMELL', 'SMILE', 'SMITH', 'SMOKE', 'SNAKE',
  'SNEAK', 'SOBER', 'SOLAR', 'SOLID', 'SOLVE', 'SORRY', 'SOUND', 'SOUTH', 'SPACE',
  'SPARE', 'SPARK', 'SPEAK', 'SPEED', 'SPELL', 'SPEND', 'SPENT', 'SPIKE', 'SPINE',
  'SPLIT', 'SPOKE', 'SPORT', 'SPRAY', 'SPREAD', 'SPRING', 'SQUAD', 'SQUARE', 'STACK',
  'STAFF', 'STAGE', 'STAIN', 'STAIR', 'STAKE', 'STALE', 'STAMP', 'STAND', 'STARK',
  'START', 'STATE', 'STEAM', 'STEEL', 'STEEP', 'STEER', 'STICK', 'STIFF', 'STILL',
  'STING', 'STOCK', 'STOLE', 'STOMP', 'STONE', 'STOOD', 'STOOL', 'STORE', 'STORM',
  'STORY', 'STOVE', 'STRAP', 'STRAW', 'STRIP', 'STUCK', 'STUDY', 'STUFF', 'STUMP',
  'STUNG', 'STUNK', 'STUNT', 'STYLE', 'SUGAR', 'SUITE', 'SUNNY', 'SUPER', 'SURGE',
  'SUSHI', 'SWEAR', 'SWEAT', 'SWEEP', 'SWEET', 'SWELL', 'SWEPT', 'SWIFT', 'SWING',
  'SWIRL', 'SWORD', 'SWORE', 'SWORN', 'TABLE', 'TAKEN', 'TASTE', 'TAXED', 'TEACH',
  'TEASE', 'TEMPO', 'TENSE', 'TENTH', 'TERMS', 'TEXAS', 'THANK', 'THEFT', 'THEIR',
  'THEME', 'THERE', 'THESE', 'THICK', 'THIEF', 'THING', 'THINK', 'THIRD', 'THORN',
  'THOSE', 'THREE', 'THREW', 'THROW', 'THUMB', 'TIGER', 'TIGHT', 'TIMER', 'TIMES',
  'TIRED', 'TITLE', 'TODAY', 'TOMMY', 'TOPIC', 'TORCH', 'TOTAL', 'TOUCH', 'TOUGH',
  'TOWEL', 'TOWER', 'TOXIC', 'TRACE', 'TRACK', 'TRADE', 'TRAIL', 'TRAIN', 'TRAIT',
  'TRASH', 'TREAD', 'TREAT', 'TREND', 'TRIAL', 'TRIBE', 'TRICK', 'TRIED', 'TROOP',
  'TROUT', 'TRUCK', 'TRULY', 'TRUNK', 'TRUST', 'TRUTH', 'TULIP', 'TUMOR', 'TUNED',
  'TWICE', 'TWIST', 'TYLER', 'UNDER', 'UNFAIR', 'UNION', 'UNITY', 'UNTIL', 'UPPER',
  'UPSET', 'URBAN', 'USAGE', 'USUAL', 'UTTER', 'VAGUE', 'VALID', 'VALUE', 'VAPOR',
  'VAULT', 'VENUE', 'VERSE', 'VIDEO', 'VIGOR', 'VILLA', 'VIRAL', 'VIRUS', 'VISIT',
  'VITAL', 'VIVID', 'VOCAL', 'VOICE', 'VOTER', 'WAGES', 'WAGON', 'WAIST', 'WASTE',
  'WATCH', 'WATER', 'WEARY', 'WEAVE', 'WEDGE', 'WEIGH', 'WEIRD', 'WHALE', 'WHEAT',
  'WHEEL', 'WHERE', 'WHICH', 'WHILE', 'WHITE', 'WHOLE', 'WHOSE', 'WIDER', 'WIDTH',
  'WINDS', 'WINDY', 'WIPER', 'WIRED', 'WITCH', 'WOMAN', 'WOMEN', 'WOODS', 'WORLD',
  'WORRY', 'WORSE', 'WORST', 'WORTH', 'WOULD', 'WOUND', 'WOVEN', 'WRATH', 'WRECK',
  'WRIST', 'WRITE', 'WRONG', 'WROTE', 'YACHT', 'YIELD', 'YOUNG', 'YOURS', 'YOUTH',
  'ZONES',
]);

/**
 * Combined word bank for fast lookup
 */
export const WORD_BANK = new Set([...FOUR_LETTER_WORDS, ...LONGER_WORDS]);

/**
 * Check if a word exists in the local word bank
 * @param word - The word to check (will be uppercased)
 * @returns True if word is in the local bank
 */
export function isInWordBank(word: string): boolean {
  return WORD_BANK.has(word.toUpperCase());
}

/**
 * Get stats about the word bank
 */
export function getWordBankStats() {
  return {
    totalWords: WORD_BANK.size,
    fourLetterWords: FOUR_LETTER_WORDS.size,
    longerWords: LONGER_WORDS.size,
  };
}
