// Common English words for hint word seeding
// These are frequently occurring words that help ensure players can find hints

export const HINT_WORD_LIBRARY = {
  3: [
    'THE', 'AND', 'FOR', 'ARE', 'BUT', 'NOT', 'YOU', 'CAN', 'HER', 'WAS',
    'ONE', 'OUR', 'OUT', 'DAY', 'GET', 'HAS', 'HIM', 'HIS', 'HOW', 'ITS',
    'MAY', 'NEW', 'NOW', 'OLD', 'SEE', 'TWO', 'WAY', 'WHO', 'BOY', 'DID',
    'LET', 'PUT', 'SAY', 'SHE', 'TOO', 'USE', 'YES', 'ACT', 'AGE', 'AGO',
    'AIR', 'ALL', 'ANY', 'ARM', 'ART', 'ASK', 'BAD', 'BAG', 'BED', 'BIG',
    'BIT', 'BOX', 'BUS', 'BUY', 'CAR', 'CAT', 'CUP', 'CUT', 'DOG', 'EAR',
    'EAT', 'END', 'EYE', 'FAR', 'FEW', 'FIT', 'FLY', 'FUN', 'GOD', 'GOT',
    'GUN', 'GUY', 'HAD', 'HAT', 'HIT', 'HOT', 'JOB', 'KEY', 'LAY', 'LEG',
    'LIE', 'LOT', 'LOW', 'MAN', 'MAP', 'MEN', 'MET', 'MIX', 'OFF', 'PAY',
    'PEN', 'PER', 'PET', 'POP', 'POT', 'RAN', 'RED', 'ROW', 'RUN', 'SAD',
    'SAT', 'SET', 'SIT', 'SIX', 'SKY', 'SON', 'SUN', 'TAX', 'TEN', 'TIE',
    'TIP', 'TOP', 'TRY', 'VAN', 'WAR', 'WAS', 'WET', 'WIN', 'WON', 'YET',
  ],
  4: [
    'ABLE', 'ALSO', 'AREA', 'BACK', 'BALL', 'BEAR', 'BEEN', 'BELL', 'BEST',
    'BIRD', 'BLUE', 'BOAT', 'BOOK', 'BOTH', 'CALL', 'CAME', 'CARD', 'CARE',
    'CASE', 'CITY', 'COME', 'COOL', 'DARK', 'DATA', 'DAYS', 'DEAR', 'DEEP',
    'DOES', 'DONE', 'DOOR', 'DOWN', 'EACH', 'EAST', 'EASY', 'EDGE', 'ELSE',
    'EVEN', 'EVER', 'EYES', 'FACE', 'FACT', 'FAIR', 'FALL', 'FARM', 'FAST',
    'FEEL', 'FEET', 'FELT', 'FILE', 'FILL', 'FIND', 'FINE', 'FIRE', 'FIRM',
    'FISH', 'FIVE', 'FLOW', 'FOOD', 'FOOT', 'FORM', 'FOUR', 'FREE', 'FROM',
    'FULL', 'GAME', 'GAVE', 'GIRL', 'GIVE', 'GLAD', 'GOES', 'GOLD', 'GONE',
    'GOOD', 'GRAY', 'GREW', 'GROW', 'HAIR', 'HALF', 'HALL', 'HAND', 'HARD',
    'HAVE', 'HEAD', 'HEAR', 'HEAT', 'HELD', 'HELP', 'HERE', 'HIGH', 'HILL',
    'HOLD', 'HOME', 'HOPE', 'HOUR', 'HUGE', 'IDEA', 'INTO', 'IRON', 'ITEM',
    'JUST', 'KEEP', 'KEPT', 'KIND', 'KING', 'KNEW', 'KNOW', 'LACK', 'LADY',
    'LAID', 'LAKE', 'LAND', 'LAST', 'LATE', 'LEAD', 'LEAF', 'LEAN', 'LEFT',
    'LESS', 'LIFE', 'LIFT', 'LIKE', 'LINE', 'LINK', 'LIST', 'LIVE', 'LOAD',
    'LONG', 'LOOK', 'LORD', 'LOSS', 'LOST', 'LOUD', 'LOVE', 'MADE', 'MAIL',
    'MAIN', 'MAKE', 'MANY', 'MARK', 'MASS', 'MEAN', 'MEET', 'MILE', 'MILK',
    'MIND', 'MINE', 'MISS', 'MODE', 'MOON', 'MORE', 'MOST', 'MOVE', 'MUCH',
    'MUST', 'NAME', 'NEAR', 'NECK', 'NEED', 'NEWS', 'NEXT', 'NICE', 'NINE',
    'NONE', 'NOON', 'NOSE', 'NOTE', 'ONCE', 'ONLY', 'OPEN', 'OVER', 'PACE',
    'PAGE', 'PAID', 'PAIN', 'PAIR', 'PALE', 'PARK', 'PART', 'PASS', 'PAST',
    'PATH', 'PEAK', 'PICK', 'PILE', 'PINE', 'PINK', 'PIPE', 'PLAN', 'PLAY',
    'PLOT', 'PLUS', 'POEM', 'POET', 'POLE', 'POND', 'POOL', 'POOR', 'PORT',
    'POST', 'POUR', 'PULL', 'PURE', 'PUSH', 'RACE', 'RAIN', 'RANG', 'RANK',
    'RARE', 'RATE', 'READ', 'REAL', 'REAR', 'REST', 'RICH', 'RIDE', 'RING',
    'RISE', 'RISK', 'ROAD', 'ROCK', 'RODE', 'ROLE', 'ROLL', 'ROOF', 'ROOM',
    'ROOT', 'ROPE', 'ROSE', 'RULE', 'RUSH', 'SAFE', 'SAID', 'SAIL', 'SAKE',
    'SALE', 'SALT', 'SAME', 'SAND', 'SANG', 'SAVE', 'SEAT', 'SEED', 'SEEK',
    'SEEM', 'SEEN', 'SELF', 'SELL', 'SEND', 'SENT', 'SETS', 'SHIP', 'SHOE',
    'SHOP', 'SHOT', 'SHOW', 'SHUT', 'SICK', 'SIDE', 'SIGN', 'SILK', 'SING',
    'SINK', 'SIZE', 'SKIN', 'SLIP', 'SLOW', 'SNOW', 'SOFT', 'SOIL', 'SOLD',
    'SOLE', 'SOME', 'SONG', 'SOON', 'SORT', 'SOUL', 'SPOT', 'STAR', 'STAY',
    'STEP', 'STOP', 'SUCH', 'SUIT', 'SURE', 'SWAM', 'SWIM', 'TAIL', 'TAKE',
    'TALE', 'TALK', 'TALL', 'TANK', 'TAPE', 'TASK', 'TEAM', 'TEAR', 'TELL',
    'TEND', 'TERM', 'TEST', 'THAN', 'THAT', 'THEM', 'THEN', 'THEY', 'THIN',
    'THIS', 'THUS', 'TIDE', 'TIED', 'TILL', 'TIME', 'TINY', 'TIRE', 'TOLD',
    'TONE', 'TOOK', 'TOOL', 'TORN', 'TOUR', 'TOWN', 'TRAP', 'TREE', 'TRIP',
    'TRUE', 'TUNE', 'TURN', 'TYPE', 'UNIT', 'UPON', 'USED', 'USER', 'VAST',
    'VERB', 'VERY', 'VIEW', 'WAIT', 'WALK', 'WALL', 'WANT', 'WARM', 'WARN',
    'WASH', 'WAVE', 'WEAK', 'WEAR', 'WEEK', 'WELL', 'WENT', 'WERE', 'WEST',
    'WHAT', 'WHEN', 'WHOM', 'WIDE', 'WIFE', 'WILD', 'WILL', 'WIND', 'WINE',
    'WING', 'WIRE', 'WISE', 'WISH', 'WITH', 'WOLF', 'WOOD', 'WOOL', 'WORD',
    'WORE', 'WORK', 'WORN', 'YARD', 'YEAR', 'YOUR', 'ZERO', 'ZONE',
  ],
  5: [
    'ABOUT', 'ABOVE', 'ADDED', 'ADMIT', 'ADOPT', 'ADULT', 'AFTER', 'AGAIN',
    'AGENT', 'AGREE', 'AHEAD', 'ALARM', 'ALBUM', 'ALERT', 'ALIEN', 'ALIGN',
    'ALIVE', 'ALLOW', 'ALONE', 'ALONG', 'ALTER', 'ANGEL', 'ANGER', 'ANGLE',
    'ANGRY', 'APART', 'APPLE', 'APPLY', 'ARENA', 'ARGUE', 'ARISE', 'ARMED',
    'ARMOR', 'AROSE', 'ARRAY', 'ARROW', 'ASIDE', 'ASSET', 'AVOID', 'AWAKE',
    'AWARD', 'AWARE', 'BADLY', 'BAKER', 'BASIC', 'BEACH', 'BEGAN', 'BEGIN',
    'BEING', 'BELOW', 'BENCH', 'BLACK', 'BLAME', 'BLANK', 'BLIND', 'BLOCK',
    'BLOOD', 'BOARD', 'BOOST', 'BOUND', 'BRAIN', 'BRAND', 'BRAVE', 'BREAD',
    'BREAK', 'BREED', 'BRIEF', 'BRING', 'BROAD', 'BROKE', 'BROWN', 'BUILD',
    'BUILT', 'BUYER', 'CABLE', 'CALIF', 'CAMEL', 'CANAL', 'CANDY', 'CARRY',
    'CATCH', 'CAUSE', 'CHAIN', 'CHAIR', 'CHAOS', 'CHARM', 'CHART', 'CHASE',
    'CHEAP', 'CHECK', 'CHEST', 'CHIEF', 'CHILD', 'CHINA', 'CHOSE', 'CIVIL',
    'CLAIM', 'CLASS', 'CLEAN', 'CLEAR', 'CLICK', 'CLIMB', 'CLOCK', 'CLOSE',
    'CLOUD', 'COACH', 'COAST', 'COLOR', 'COUCH', 'COULD', 'COUNT', 'COURT',
    'COVER', 'CRACK', 'CRAFT', 'CRASH', 'CRAZY', 'CREAM', 'CRIME', 'CROSS',
    'CROWD', 'CROWN', 'CRUDE', 'CURVE', 'CYCLE', 'DAILY', 'DANCE', 'DATED',
    'DEALT', 'DEATH', 'DEBUT', 'DELAY', 'DELTA', 'DENSE', 'DEPTH', 'DOING',
    'DOUBT', 'DOZEN', 'DRAFT', 'DRAFT', 'DRAMA', 'DRANK', 'DRAWN', 'DREAM',
    'DRESS', 'DRIED', 'DRIFT', 'DRILL', 'DRINK', 'DRIVE', 'DROVE', 'DYING',
    'EAGER', 'EARLY', 'EARTH', 'EIGHT', 'ELECT', 'EMPTY', 'ENEMY', 'ENJOY',
    'ENTER', 'ENTRY', 'EQUAL', 'ERROR', 'EVENT', 'EVERY', 'EXACT', 'EXIST',
    'EXTRA', 'FAITH', 'FALSE', 'FAULT', 'FIBER', 'FIELD', 'FIFTH', 'FIFTY',
    'FIGHT', 'FINAL', 'FIRST', 'FIXED', 'FLASH', 'FLEET', 'FLOOR', 'FLUID',
    'FOCUS', 'FORCE', 'FORTH', 'FORTY', 'FORUM', 'FOUND', 'FRAME', 'FRANK',
    'FRAUD', 'FRESH', 'FRONT', 'FRUIT', 'FULLY', 'FUNNY', 'GIANT', 'GIVEN',
    'GLASS', 'GLOBE', 'GOING', 'GRACE', 'GRADE', 'GRAND', 'GRANT', 'GRASS',
    'GREAT', 'GREEN', 'GROSS', 'GROUP', 'GROWN', 'GUARD', 'GUESS', 'GUEST',
    'GUIDE', 'HAPPY', 'HARRY', 'HEART', 'HEAVY', 'HENCE', 'HENRY', 'HORSE',
    'HOTEL', 'HOUSE', 'HUMAN', 'IDEAL', 'IMAGE', 'INDEX', 'INNER', 'INPUT',
    'ISSUE', 'JAPAN', 'JIMMY', 'JOINT', 'JONES', 'JUDGE', 'KNOWN', 'LABEL',
    'LARGE', 'LASER', 'LATER', 'LAUGH', 'LAYER', 'LEARN', 'LEASE', 'LEAST',
    'LEAVE', 'LEGAL', 'LEMON', 'LEVEL', 'LEWIS', 'LIGHT', 'LIMIT', 'LINKS',
    'LOCAL', 'LOGIC', 'LOOSE', 'LOWER', 'LUCKY', 'LUNCH', 'LYING', 'MAGIC',
    'MAJOR', 'MAKER', 'MARCH', 'MARIA', 'MATCH', 'MAYBE', 'MAYOR', 'MEANT',
    'MEDAL', 'MEDIA', 'METAL', 'MIGHT', 'MINOR', 'MINUS', 'MIXED', 'MODEL',
    'MONEY', 'MONTH', 'MORAL', 'MOTOR', 'MOUNT', 'MOUSE', 'MOUTH', 'MOVED',
    'MOVIE', 'MUSIC', 'NEEDS', 'NEVER', 'NIGHT', 'NOISE', 'NORTH', 'NOTED',
    'NOVEL', 'NURSE', 'OCCUR', 'OCEAN', 'OFFER', 'OFTEN', 'ORDER', 'OTHER',
    'OUGHT', 'OUTER', 'OWNER', 'PAINT', 'PANEL', 'PAPER', 'PARIS', 'PARTY',
    'PEACE', 'PETER', 'PHASE', 'PHONE', 'PHOTO', 'PIANO', 'PIECE', 'PILOT',
    'PITCH', 'PLACE', 'PLAIN', 'PLANE', 'PLANT', 'PLATE', 'PLAZA', 'POINT',
    'POKER', 'POLICE', 'POUND', 'POWER', 'PRESS', 'PRICE', 'PRIDE', 'PRIME',
    'PRINT', 'PRIOR', 'PRIZE', 'PROOF', 'PROUD', 'PROVE', 'QUEEN', 'QUICK',
    'QUIET', 'QUITE', 'QUOTE', 'RADIO', 'RAISE', 'RANGE', 'RAPID', 'RATIO',
    'REACH', 'READY', 'REFER', 'RIGHT', 'RIVER', 'ROMAN', 'ROUGH', 'ROUND',
    'ROUTE', 'ROYAL', 'RURAL', 'SCALE', 'SCENE', 'SCOPE', 'SCORE', 'SENSE',
    'SERVE', 'SEVEN', 'SHALL', 'SHAPE', 'SHARE', 'SHARP', 'SHEET', 'SHELF',
    'SHELL', 'SHIFT', 'SHINE', 'SHIRT', 'SHOCK', 'SHOOT', 'SHORT', 'SHOWN',
    'SIGHT', 'SINCE', 'SIXTH', 'SIXTY', 'SIZED', 'SKILL', 'SLEEP', 'SLIDE',
    'SMALL', 'SMART', 'SMILE', 'SMITH', 'SMOKE', 'SOLID', 'SOLVE', 'SORRY',
    'SOUND', 'SOUTH', 'SPACE', 'SPARE', 'SPEAK', 'SPEED', 'SPEND', 'SPENT',
    'SPLIT', 'SPOKE', 'SPORT', 'STAFF', 'STAGE', 'STAKE', 'STAND', 'START',
    'STATE', 'STEAM', 'STEEL', 'STICK', 'STILL', 'STOCK', 'STONE', 'STOOD',
    'STORE', 'STORM', 'STORY', 'STRIP', 'STUCK', 'STUDY', 'STUFF', 'STYLE',
    'SUGAR', 'SUITE', 'SUPER', 'SWEET', 'TABLE', 'TAKEN', 'TASTE', 'TAXES',
    'TEACH', 'TEETH', 'TERRY', 'TEXAS', 'THANK', 'THEFT', 'THEIR', 'THEME',
    'THERE', 'THESE', 'THICK', 'THING', 'THINK', 'THIRD', 'THOSE', 'THREE',
    'THREW', 'THROW', 'TIGHT', 'TIMES', 'TITLE', 'TODAY', 'TOPIC', 'TOTAL',
    'TOUCH', 'TOUGH', 'TOWER', 'TRACK', 'TRADE', 'TRAIL', 'TRAIN', 'TRAIT',
    'TREAT', 'TREND', 'TRIAL', 'TRIBE', 'TRICK', 'TRIED', 'TRIES', 'TROOP',
    'TRUCK', 'TRULY', 'TRUNK', 'TRUST', 'TRUTH', 'TWICE', 'UNCLE', 'UNDER',
    'UNDUE', 'UNION', 'UNITY', 'UNTIL', 'UPPER', 'UPSET', 'URBAN', 'USAGE',
    'USUAL', 'VALID', 'VALUE', 'VIDEO', 'VIRUS', 'VISIT', 'VITAL', 'VOCAL',
    'VOICE', 'WASTE', 'WATCH', 'WATER', 'WHEEL', 'WHERE', 'WHICH', 'WHILE',
    'WHITE', 'WHOLE', 'WHOSE', 'WOMAN', 'WOMEN', 'WORLD', 'WORRY', 'WORSE',
    'WORST', 'WORTH', 'WOULD', 'WOUND', 'WRITE', 'WRONG', 'WROTE', 'YIELD',
    'YOUNG', 'YOUTH',
  ],
};

// High frequency letters for smart filling (in order of frequency in English)
export const HIGH_FREQ_LETTERS = 'ETAOINSHRDLCUMWFGYPBVKJXQZ';

// Common letter pairs (digraphs) that form words easily
export const COMMON_DIGRAPHS = [
  'TH', 'HE', 'IN', 'ER', 'AN', 'RE', 'ON', 'AT', 'EN', 'ND',
  'TI', 'ES', 'OR', 'TE', 'OF', 'ED', 'IS', 'IT', 'AL', 'AR',
  'ST', 'TO', 'NT', 'NG', 'SE', 'HA', 'AS', 'OU', 'IO', 'LE',
];
